Auction-shop-project/As_BE

src/main/java/Auction_shop/auction/domain/member/Address.java
src/main/java/Auction_shop/auction/domain/member/Member.java
src/main/java/Auction_shop/auction/domain/member/controller/MemberController.java
src/main/java/Auction_shop/auction/domain/member/repository/MemberRepository.java
src/main/java/Auction_shop/auction/domain/member/service/MemberService.java
src/main/java/Auction_shop/auction/domain/refreshToken/RefreshToken.java
src/main/java/Auction_shop/auction/domain/refreshToken/repository/RefreshTokenRepository.java
src/main/java/Auction_shop/auction/redis/config/RedisConfig.java
src/main/java/Auction_shop/auction/security/CustomUserDetails.java
src/main/java/Auction_shop/auction/security/MemberSecurity.java
src/main/java/Auction_shop/auction/security/auth/controller/AuthController.java
src/main/java/Auction_shop/auction/security/auth/service/AuthService.java
src/main/java/Auction_shop/auction/security/config/CorsMvcConfig.java
src/main/java/Auction_shop/auction/security/config/SecurityConfig.java
src/main/java/Auction_shop/auction/security/jwt/CustomLogoutFilter.java
src/main/java/Auction_shop/auction/security/jwt/JwtFilter.java
src/main/java/Auction_shop/auction/security/jwt/JwtUtil.java
src/main/java/Auction_shop/auction/web/dto/AuthRequestDto.java
src/main/java/Auction_shop/auction/web/dto/AuthResponseDto.java
src/main/java/Auction_shop/auction/web/dto/MemberResponseDto.java
src/main/java/Auction_shop/auction/web/dto/MemberUpdateDto.java

회원 기능 구현, JWT 구현 (CORS 설정 미구현)

회원 기능 구현, JWT 구현

---

src/main/java/Auction_shop/auction/domain/member/Member.java
src/main/java/Auction_shop/auction/product/controller/ProductController.java
src/main/java/Auction_shop/auction/product/domain/Product.java
src/main/java/Auction_shop/auction/product/dto/ProductDto.java
src/main/java/Auction_shop/auction/product/dto/ProductListResponseDto.java
src/main/java/Auction_shop/auction/product/dto/ProductResponseDto.java
src/main/java/Auction_shop/auction/product/service/ProductService.java
src/main/java/Auction_shop/auction/product/service/ProductServiceImpl.java

기존 ProductService 코드를 일부 바꾸고 Controller단에 List조회 기능을 추가했습니다
한 번 확인 부탁드립니다!

상품 리스트 조회 기능 추가 및 이미지 기능 추가

---

README.md

test: Readme 파일 수정

---

.github/workflows/develop.yml

TOKEN -> GH_TOKEN으로 수정
참고 링크
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

chore: develop.yml 파일 수정

---

.github/workflows/develop.yml

chore: Actions runner 실행 권한 부여

---

README.md

etc: README file 변경

---

src/main/java/Auction_shop/auction/domain/inquriy/Inquiry.java
src/main/java/Auction_shop/auction/domain/member/Member.java

inquiry 클래스의 private List<Image> imageList = new ArrayList<>();
Member 클래스의 private boolean available = false;
@builder 어노테이션을 @builder.Default로 수정

fix: Inquiry,Member 클래스 @Builder 수정

---

.github/workflows/develop.yml
README.md
src/main/java/Auction_shop/auction/domain/inquriy/Inquiry.java
src/main/java/Auction_shop/auction/domain/member/Member.java

로그 확인 위해 ./gradle build에 -i --stacktrace 추가
Inquiry,Member 클래스에 @builder 어노테이션 추가

Workflow 에러 수정

---

src/main/java/Auction_shop/auction/AuctionApplication.java
src/main/java/Auction_shop/auction/product/domain/Product.java
src/main/java/Auction_shop/auction/product/dto/ProductDto.java
src/main/java/Auction_shop/auction/product/dto/ProductResponseDto.java
src/main/java/Auction_shop/auction/product/repository/ProductRepository.java
src/main/java/Auction_shop/auction/product/service/ProductService.java
src/main/java/Auction_shop/auction/product/service/ProductServiceImpl.java

redis 사용해서 성능 최적화 예정
webSocket 사용해서 실시간 기능 구현 예정

Feat: 하향식 경매 기능 구현

---

src/main/java/Auction_shop/auction/domain/inquriy/Inquiry.java
src/main/java/Auction_shop/auction/domain/inquriy/controller/InquiryController.java
src/main/java/Auction_shop/auction/domain/inquriy/repository/InquiryRepository.java
src/main/java/Auction_shop/auction/domain/inquriy/service/InquiryService.java
src/main/java/Auction_shop/auction/domain/member/Member.java
src/main/java/Auction_shop/auction/product/controller/HistoryController.java
src/main/java/Auction_shop/auction/product/controller/ProductController.java
src/main/java/Auction_shop/auction/product/domain/Product.java
src/main/java/Auction_shop/auction/product/dto/ProductDto.java
src/main/java/Auction_shop/auction/product/dto/ProductListResponseDto.java
src/main/java/Auction_shop/auction/product/dto/ProductResponseDto.java
src/main/java/Auction_shop/auction/product/repository/ProductRepository.java
src/main/java/Auction_shop/auction/product/service/ProductService.java
src/main/java/Auction_shop/auction/product/service/ProductServiceImpl.java
src/main/java/Auction_shop/auction/product/validation/ProductValidator.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryCreateDto.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryListResponseDto.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryMapper.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryMapperImpl.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryResponseDto.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryUpdateDto.java

Feat: member, product 매핑 및 구매 기능 추가

---

appspec.yml
deploy.sh

appspec.yml에 hooks 추가
deploy.sh 파일 생성

feat: appspec.yml, deploy.sh 내용 추가

---

appspec.yml

덮어쓰기를 통해 배포 과정의 install 실패 해결 중

fix: appspec.yml 파일 수정

---

src/main/java/Auction_shop/auction/DeployTest.java

배포 테스트용 클래스 추가, 성공 시 Deploy Success :) 반환

feat: DeployTest 클래스 추가

---

appspec.yml
deploy.sh
src/main/resources/application.yml

fix: appspec.yml 수정

---

deploy.sh

fix: deploy.sh 수정

---

src/main/java/Auction_shop/auction/domain/member/controller/MemberController.java

request) access token -> memberId로 수정

fix: updateMember 오류 수정

---

src/main/java/Auction_shop/auction/domain/product/service/ProductServiceImpl.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryListResponseDto.java
src/main/java/Auction_shop/auction/web/dto/inquiry/InquiryMapperImpl.java

1. 물건 조회 시 product_id 높은 순으로 정렬 (최신 순으로 조회를 위함)
2. 문의 리스트 조회 시 이미지 리스트로 반환

Feat: 문의, 물건 조회 일부 로직 수정

---

build.gradle
src/main/java/Auction_shop/auction/swagger/config/swaggerConfig.java

http://{서버_IP}:8080/swagger-ui/index.html 로 접속 가능

Feat: Swagger 도입

---

src/main/java/Auction_shop/auction/domain/member/Member.java
src/main/java/Auction_shop/auction/domain/member/controller/MemberController.java
src/main/java/Auction_shop/auction/domain/member/repository/MemberRepository.java
src/main/java/Auction_shop/auction/domain/member/service/MemberService.java

낙관적 락을 적용해 사용자가 몰려서 닉네임이 중복 등록이 되는 걸 방지함

Feat: Member 닉네임 중복 검증 추가

---

src/main/java/Auction_shop/auction/domain/member/controller/MemberController.java

닉네임 검증 api가 서버에 제대로 반영이 안 된 거 같아 pr 다시 올렸습니다

membername Check test

---

src/main/java/Auction_shop/auction/domain/product/Product.java
src/main/java/Auction_shop/auction/domain/product/service/ProductServiceImpl.java
src/main/java/Auction_shop/auction/domain/product/validation/ProductValidator.java
src/main/java/Auction_shop/auction/web/dto/product/ProductDto.java

product_Type -> categories로 대체

Feat: 이미지 수정 로직 변경 및 product_Type 속성 삭제

---

src/main/java/Auction_shop/auction/domain/member/Member.java
src/main/java/Auction_shop/auction/domain/member/service/MemberService.java

첫 로그인 시 nickname, email은 uuid를 따라가게 수정

Fix: 유저 생성 안 되는 버그 픽스

---

src/main/java/Auction_shop/auction/chat/controller/ChatController.java
src/main/java/Auction_shop/auction/chat/domain/Chat.java
src/main/java/Auction_shop/auction/chat/dto/ChatDto.java
src/main/java/Auction_shop/auction/chat/service/ChatServiceImpl.java
src/main/java/Auction_shop/auction/chatRoom/controller/ChatRoomController.java

메세지만 전달 - > 채팅테이블 컬럼 값 전부 응답(id,roomId,userId,message,createdAt)

Fix: 채팅 전달 수정

---

.gitignore
src/main/java/Auction_shop/auction/chatRoom/controller/ChatRoomController.java

ChatRoomController의 Controller 어노테이션 RestController 어노테이션으로 수정
.gitignore에 application.yml 추가

Fix: ChatRoomController 수정, .gitignore 수정

---

src/main/java/Auction_shop/auction/chat/domain/Chat.java
src/main/java/Auction_shop/auction/chat/dto/ChatDto.java
src/main/java/Auction_shop/auction/chat/repository/ChatRepository.java
src/main/java/Auction_shop/auction/chatRoom/controller/ChatRoomController.java
src/main/java/Auction_shop/auction/chatRoom/domain/ChatRoom.java
src/main/java/Auction_shop/auction/chatRoom/dto/ChatRoomDto.java
src/main/java/Auction_shop/auction/chatRoom/dto/ChatRoomListResponseDto.java
src/main/java/Auction_shop/auction/chatRoom/repository/ChatRoomRepository.java
src/main/java/Auction_shop/auction/chatRoom/service/ChatRoomService.java
src/main/java/Auction_shop/auction/chatRoom/service/ChatRoomServiceImpl.java
src/main/java/Auction_shop/auction/domain/alert/util/AlertUtil.java
src/main/java/Auction_shop/auction/sse/SSEConnection.java

기존 유저ID, 상대방ID, 게시글ID, 방번호에 추가로
물품 이미지URL, 상대방 프로필 URL, 상대방 닉네임
마지막 채팅시간, 마지막 채팅 내역 전달

fix: 채팅방 목록 조회 수정

---

src/main/java/Auction_shop/auction/domain/bid/Bid.java
src/main/java/Auction_shop/auction/domain/bid/BidStatus.java
src/main/java/Auction_shop/auction/domain/bid/BidType.java
src/main/java/Auction_shop/auction/domain/bid/repository/BidJpaRepository.java
src/main/java/Auction_shop/auction/domain/bid/repository/BidRedisRepository.java
src/main/java/Auction_shop/auction/domain/bid/service/BidService.java
src/main/java/Auction_shop/auction/domain/payments/service/AscendingPaymentService.java
src/main/java/Auction_shop/auction/domain/product/service/ProductServiceImpl.java
src/main/java/Auction_shop/auction/web/dto/bid/BidMapperImpl.java
src/main/java/Auction_shop/auction/web/dto/bid/BidResponseDto.java
src/main/java/Auction_shop/auction/web/dto/bid/MemberBidListResponseDto.java

isTopBid 삭제 및 BidStatus 추가
SUCCESS (낙찰), FAILED (더 높은 금액으로 입찰 들어와 실패), PROGRESS (유력)

Feat: Bid 상태 반환 변수 추가

---

src/main/java/Auction_shop/auction/domain/member/Member.java
src/main/java/Auction_shop/auction/domain/member/controller/MemberController.java
src/main/java/Auction_shop/auction/domain/member/repository/MemberRepository.java
src/main/java/Auction_shop/auction/domain/member/service/MemberService.java
src/main/java/Auction_shop/auction/domain/product/ProductDocument.java
src/main/java/Auction_shop/auction/domain/product/controller/ProductController.java
src/main/java/Auction_shop/auction/domain/product/elasticRepository/ProductElasticsearchRepository.java
src/main/java/Auction_shop/auction/domain/product/repository/ProductJpaRepository.java
src/main/java/Auction_shop/auction/domain/product/service/ProductService.java
src/main/java/Auction_shop/auction/domain/product/service/ProductServiceImpl.java
src/main/java/Auction_shop/auction/web/dto/product/ProductMapplerImpl.java

1. 물건 구매 성공 시 입찰자 포인트 +1000 (이후 구매 확정 기능 구현하면 판매자에게도 포인트 증정)
2. 포인트 명예의 전당 기능 구현

Feat: 포인트 관련 기능 구현

---

src/main/java/Auction_shop/auction/domain/bid/controller/BidController.java
src/main/java/Auction_shop/auction/domain/product/Product.java
src/main/java/Auction_shop/auction/domain/product/service/ProductServiceImpl.java
src/main/java/Auction_shop/auction/web/dto/bid/BidMapperImpl.java
src/main/java/Auction_shop/auction/web/dto/product/ProductUpdateDto.java

1. memberBIdList 반환 시 bidTime 반환
2. product 수정 시 tradeType 수정 가능하게 변경

Feat: memberBidList 반환 값 추가 및 product 수정 변경

---

src/main/java/Auction_shop/auction/chat/dto/ChatLogDto.java
src/main/java/Auction_shop/auction/chat/repository/ChatRepository.java
src/main/java/Auction_shop/auction/chatRoom/dto/ChatRoomInfoResponseDto.java
src/main/java/Auction_shop/auction/chatRoom/service/ChatRoomServiceImpl.java

roomId를 제외한  채팅 로그 받아오는 ChatLogDto 추가
Repository,service 단의 ChatDto를 ChatLogDto로 수정

fix: roomId를 chatLog 외부로 빼서 응답하도록  수정

---

src/main/java/Auction_shop/auction/chatRoom/controller/ChatRoomController.java
src/main/java/Auction_shop/auction/chatRoom/dto/ChatRoomCreateResponseDto.java

ChatRoomCreateResponseDto에 newChatRoomId를 담아 전달

fix: 채팅방 생성 Json 타입으로 전달하도록 수정

---

.github/workflows/develop.yml

fix: workflows/develop.yml 수정

---

src/main/java/Auction_shop/auction/sse/SSEConnection.java

SSE를 잘 몰라 확실하지 않아 확인 후 오류 해결이 안 되면 롤백 예정

fix: SSE 끊김 오류 수정

---

src/main/java/Auction_shop/auction/chatRoom/controller/ChatRoomController.java
src/main/java/Auction_shop/auction/chatRoom/dto/ChatRoomCreateResponseDto.java

fix: ChatRoomCreateResponseDto 멤버 변수명 변경

---

src/main/java/Auction_shop/auction/AuctionApplication.java
src/main/java/Auction_shop/auction/chat/controller/ChatController.java
src/main/java/Auction_shop/auction/chat/service/ChatServiceImpl.java
src/main/java/Auction_shop/auction/chatRoom/controller/ChatRoomController.java
src/main/java/Auction_shop/auction/chatRoom/repository/ChatRoomRepository.java
src/main/java/Auction_shop/auction/chatRoom/service/ChatRoomService.java
src/main/java/Auction_shop/auction/chatRoom/service/ChatRoomServiceImpl.java

채팅방 DB 삭제 구현
퇴장한 상대방에게 채팅 시 다시 초대하는 과정 미완성

feat: 채팅방 퇴장 추가

---

src/main/java/Auction_shop/auction/chat/controller/ChatController.java
src/main/java/Auction_shop/auction/chat/domain/Chat.java

상대방이 나간 상태에서 남아있는 사용자가 채팅을 보낼 경우 상대방을 자동으로 채팅방에 다시 초대

feat: 재초대 기능 구현
